---
title: "Pitch Correlation Final"
author: "Riley Feltner"
date: "7/25/2022"
output: html_document
---

#min= qualifying pitchers
```{r}
mydata <- read.csv("FanGraphsLeaderboard.csv") #FanGraphs "Dashboard Stats"
mydata1 <- read.csv("FanGraphsLeaderboard(1).csv") #FanGraphs "Advanced" Stats
```



#load requires packages and libraries
```{r}
#install.packages("metan")
library(metan)
library(ggplot2)
#install.packages("ggcorrplot")
library(ggcorrplot)
```

#select variables and create matrix
```{r}
mydata2 <- mydata[,c(1,3, 9:12, 17:21)]
mydata3 <- mydata1[,c(1,10:11, 21)]
mydata4 <- merge(mydata2, mydata3, by = "Name") 
mydatamatrix <- as.matrix(mydata2)
mydata5 <- mydata4[,c(-1)]
cor(mydata5)
cor = round(cor(mydata5), 2)
cor
```

#apply the ggcorrplot() function

```{r}
c = ggcorrplot(cor,
           title = "2022 MLB Pitching Stats Correlation Matrix", 
           lab = TRUE,
           lab_size = 2.2,
           hc.order = TRUE)
cthemes <- c+theme(axis.text.x = element_text(size = 7), axis.text.y = element_text(size = 7))
cthemes+labs(caption = "Data: FanGraphs | Riley Feltner",
             subtitle = "Qualified Starting Pitchers")

```


